name: Create Source Code Zip

on:
  push:
    branches: [main]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create source code zip
      run: |
        echo "Creating complete source code archive..."
        zip -r shuaib-rohani-clinic-complete.zip . -x "*.git*"
        ls -lh *.zip
        echo "Zip file created successfully!"
        
    - name: Upload Complete Source Code
      uses: actions/upload-artifact@v4
      with:
        name: complete-source-zip
        path: shuaib-rohani-clinic-complete.zip
        retention-days: 30
